---
- name: Ensure database user 'jira' exists
  postgresql_user:
    name: jira
    password: jira
    role_attr_flags: NOSUPERUSER,NOCREATEDB
  tags: test

- name: Ensure database 'jira' is existing
  postgresql_db:
    name: jira
    owner: jira
    port: 5432
    state: present
    encoding: UTF-8
    # lc_collate: de_DE.UTF-8
    # lc_ctype: de_DE.UTF-8
  tags: test