- name: Download Jira Installer
  get_url:
    url: "{{ jira_installer_url }}"
    dest: "{{ jira_installation_dir}}"
- name: Make Jira Installer executable
  file:
    dest: "{{ jira_installation_dir}}/{{ jira_installer_name }}"
    mode: a+x
- name: Extract Jira Archive
  unarchive:
    src: "{{ jira_installation_dir}}/{{ jira_installer_name }}"
    dest: "{{ jira_installation_dir}}"
    remote_src: yes
- name: Add Jira group
  group:
    name: "{{ jira_user }}"
    state: present
  tags: test
- name: Add Jira User
  user:
    name: "{{ jira_user }}"
    group: "{{ jira_user_group }}"
  tags: test
