- name: Download Jira Installer
  get_url:
    url: "{{ jira_installer_url }}"
    dest: "{{ tmp}}/{{ jira_installer_name }}"

- name: Make Jira Installer executable
  file:
    path: "{{ tmp}}/{{ jira_installer_name }}"
    mode: a+x

- name: Create response.varfile for Jira Installation
  template:
    src: response.varfile.j2
    dest: "{{ tmp }}/response.varfile"

- name: Run Jira Installer
  command: "{{ tmp}}/{{ jira_installer_name }} -q -varfile response.varfile"