---
- import_tasks: preperation.yml
- include_tasks: installation.yml
  when: (jiraFolder.stat.exists == false or jiraHasNewerVersion.changed == true)
- import_tasks: backup.yml

- import_tasks: configure-reverseproxy.yml
  when: jiraWithReverseProxy == true

- import_tasks: database.yml
  become_user: postgres
  vars: 
    ansible_ssh_pipelining: true
