- name: Ensure Atlassian folder exists
  file: 
    path: "{{ jira_installation_root }}"
    state: directory

- name: Download Jira Installer
  get_url:
    url: "{{ jira_installer_url }}"
    dest: "{{ jira_installer_fullpath }}"

- name: Make Jira Installer executable
  file:
    path: "{{ jira_installer_fullpath }}"
    mode: a+x

- name: Ansible check, if jira folder exists
  stat:
    path: "{{ jira_installation_root }}/jira"
  register: jira_exists

- name: Create response.varfile for Jira quiet installation
  template:
    src: response.varfile.j2
    dest: "{{ jira_installation_root }}/response.varfile"

- name: Installation/Upgrade of Jira
  command: "{{ jira_installer_fullpath }} -q -varfile response.varfile"