---
- name: Ensure Jira installer folder exists
  file: 
    path: "{{ jira_installer_folder }}"
    state: directory

- name: Download Jira Installer
  get_url:
    url: "{{ jira_installer_url }}"
    dest: "{{ jira_installer_fullpath }}"
  register: jiraHasNewerVersion

- name: Make Jira Installer executable
  file:
    path: "{{ jira_installer_fullpath }}"
    mode: a+x
  when: jiraHasNewerVersion.changed == true

- name: Check if Jira folder exists
  stat:
    path: "{{ jira_installation_folder }}"
  register: jiraFolder
  